# **Data Cleaning**

**Check for missing values.**

In [24]:
import pandas as pd

df = pd.read_excel("/content/student_performance.xlsx")

print(df.info())
print("\n-------------------------------\n")
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Student_ID        400 non-null    object
 1   Name              400 non-null    object
 2   Gender            399 non-null    object
 3   Age               399 non-null    float64
 4   Attendance        398 non-null    float64
 5   Study_Hours       398 non-null    float64
 6   Math              399 non-null    float64
 7   English           399 non-null    float64
 8   Science           399 non-null    float64
 9   Python            398 non-null    float64
 10  Machine_Learning  399 non-null    float64
 11  Assignments       399 non-null    float64
 12  Result            400 non-null    object
dtypes: float64(9), object(4)
memory usage: 40.8+ KB
None

-------------------------------

Student_ID          0
Name                0
Gender              1
Age                 1
Attendance          2
Study_Hours         2
Math                1
English             1
Science             1
Python              2
Machine_Learning    1
Assignments         1
Result              0
dtype: int64

**Remove duplicate records (if any).
Rename one or more columns.**

In [25]:
df.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
395    False
396    False
397    False
398    False
399    False
Length: 400, dtype: bool

In [26]:
df.duplicated().sum()

np.int64(0)

In [27]:
df.columns

Index(['Student_ID', 'Name', 'Gender', 'Age', 'Attendance', 'Study_Hours',
       'Math', 'English', 'Science', 'Python', 'Machine_Learning',
       'Assignments', 'Result'],
      dtype='object')

In [28]:
df.rename(columns={"Math" : "Mathematics" , "Python" : "Python_Lingo"})

,Student_ID,Name,Gender,Age,Attendance,Study_Hours,Mathematics,English,Science,Python_Lingo,Machine_Learning,Assignments,Result
0,S001,Fatima,Female,24.0,81.0,4.0,58.0,72.0,89.0,79.0,86.0,3.0,Pass
1,S002,Ahmed,Male,24.0,86.0,6.5,79.0,92.0,66.0,69.0,67.0,8.0,Pass
2,S003,Hassan,Male,18.0,78.0,4.2,55.0,82.0,55.0,66.0,66.0,5.0,Pass
3,S004,Ayesha,Female,19.0,79.0,2.3,63.0,58.0,73.0,76.0,52.0,9.0,Pass
4,S005,Zainab,Female,21.0,88.0,2.0,72.0,91.0,42.0,69.0,68.0,3.0,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,S396,Ahmed,Male,25.0,90.0,3.4,73.0,93.0,74.0,70.0,69.0,9.0,Pass
396,S397,Fahad,Male,21.0,86.0,2.0,81.0,84.0,49.0,93.0,67.0,7.0,Pass
397,S398,Ibrahim,Male,21.0,86.0,6.4,73.0,72.0,56.0,80.0,59.0,4.0,Pass
398,S399,Bilal,Male,23.0,63.0,2.5,53.0,86.0,100.0,76.0,71.0,10.0,Pass
399,S400,Mehwish,Female,21.0,95.0,3.6,64.0,79.0,64.0,89.0,69.0,5.0,Pass

**Create a new column named Average_Score by calculating the average marks across all subjects.**

In [29]:
df.head()

,Student_ID,Name,Gender,Age,Attendance,Study_Hours,Math,English,Science,Python,Machine_Learning,Assignments,Result
0,S001,Fatima,Female,24.0,81.0,4.0,58.0,72.0,89.0,79.0,86.0,3.0,Pass
1,S002,Ahmed,Male,24.0,86.0,6.5,79.0,92.0,66.0,69.0,67.0,8.0,Pass
2,S003,Hassan,Male,18.0,78.0,4.2,55.0,82.0,55.0,66.0,66.0,5.0,Pass
3,S004,Ayesha,Female,19.0,79.0,2.3,63.0,58.0,73.0,76.0,52.0,9.0,Pass
4,S005,Zainab,Female,21.0,88.0,2.0,72.0,91.0,42.0,69.0,68.0,3.0,Pass

In [30]:
df["Average_Score"] = df.iloc[: , 6:12].mean(axis=1)

df.head()

,Student_ID,Name,Gender,Age,Attendance,Study_Hours,Math,English,Science,Python,Machine_Learning,Assignments,Result,Average_Score
0,S001,Fatima,Female,24.0,81.0,4.0,58.0,72.0,89.0,79.0,86.0,3.0,Pass,64.500000
1,S002,Ahmed,Male,24.0,86.0,6.5,79.0,92.0,66.0,69.0,67.0,8.0,Pass,63.500000
2,S003,Hassan,Male,18.0,78.0,4.2,55.0,82.0,55.0,66.0,66.0,5.0,Pass,54.833333
3,S004,Ayesha,Female,19.0,79.0,2.3,63.0,58.0,73.0,76.0,52.0,9.0,Pass,55.166667
4,S005,Zainab,Female,21.0,88.0,2.0,72.0,91.0,42.0,69.0,68.0,3.0,Pass,57.500000

**Create another column named Performance using the following criteria:

  
Excellent → Average Score ≥ 90
Good → Average Score between 80 and 89
Average → Average Score between 70 and 79
Needs Improvement → Average Score below 70.**

In [31]:
import numpy as np

conditions = [
    (df['Average_Score'] >= 90),
    (df['Average_Score'] >= 80) & (df['Average_Score'] < 90),
    (df['Average_Score'] >= 70) & (df['Average_Score'] < 80)
]
choices = ['Excellent', 'Good', 'Average']

df['Performance'] = np.select(conditions, choices, default='Needs Improvement')

In [32]:
print(df["Performance"])

0      Needs Improvement
1      Needs Improvement
2      Needs Improvement
3      Needs Improvement
4      Needs Improvement
             ...
395    Needs Improvement
396    Needs Improvement
397    Needs Improvement
398    Needs Improvement
399    Needs Improvement
Name: Performance, Length: 400, dtype: object